## read pruducts
GET http://localhost:4000/product-api/products

### read product by id
GET http://localhost:4000/product-api/products/69ae6e045a21218bffc89d35

### create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productId":1,
    "productName":"laptop",
    "price":45000,
    "brand":"MSI"
}


### update product
PUT http://localhost:4000/product-api/products/69ae6e045a21218bffc89d35
Content-Type: application/json

{
    "productId":1,
    "productName":"mobile",
    "price":4556,
    "brand":"MSI"
}


### delete product by id
DELETE http://localhost:4000/product-api/products/69ae6e045a21218bffc89d35





